#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Editor
export EDITOR=vim
export SUDO_EDITOR=rvim
export DIFFPROG=meld

# Custom
alias backlight='xrandr --output LVDS1 --set BACKLIGHT'

# Local path
path+=~/.local/bin
path=($^path(N))

# Reboot / Halt
function uhalt {
	poweroff
	exit
}
function ureboot {
	reboot
	exit
}

# Home
function o {
	xdg-open "$@" &|
}
function music {
	cd ~/user/music/current
	vlc . &|
}

# Work config
function output_flame_graph () {
	# Generate a svg, open if if no path specified
	default_output="/tmp/flamegraph.svg"
	output="${1:-${default_output}}"
	perf script | stackcollapse-perf.pl | flamegraph.pl >! "$output"
	if [[ "$output" == "$default_output" ]]; then
		chromium "$output"
	fi
}
function output_gprof2dot () {
	# Generate png, just show it if no path specified
	if [[ -z "$1" ]]; then
		perf script | c++filt | gprof2dot.py -f perf | dot -Tpng | feh -
	else
		perf script | c++filt | gprof2dot.py -f perf | dot -Tpng >! $1
	fi
}
function bpp_format () {
	bpp_format.py a "Francois Gindraud (2017)" "$@"
}
