#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Editor
export EDITOR=vim
export SUDO_EDITOR=rvim

# Custom
alias o='kde-open'
alias backlight='xrandr --output LVDS1 --set BACKLIGHT'
alias vimo='vim -O'

# Local path
path+=~/.local/bin
path=($^path(N))

# Reboot / Halt
function uhalt {
	poweroff
	exit
}
function ureboot {
	reboot
	exit
}

